version: 0.2

phases:
  # install:
  #   runtime-versions:
  #     docker: 18
  #   commands:
  #     # Installing AWS CLI (if needed) and Docker
  #     # - echo Installing AWS CLI...
  #     # - apt-get update -y && apt-get install -y awscli
  #     # - yum install -y curl 
  #     # - echo Installing Docker...
  #     # - curl -fsSL https://get.docker.com -o get-docker.sh
  #     # - sh get-docker.sh
  #     # - docker --version
      
  pre_build:
    commands:
      - echo Setting up environment...
      - aws --version
      - echo Logging into Amazon ECR...
      # Log in to ECR
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 522814711764.dkr.ecr.us-east-1.amazonaws.com


  build:
    commands:
      - echo Building Docker images for all services...
      # Build Docker images for each microservice
      - docker build -t feed ./feed_service
      - docker build -t user ./user_service
      - docker build -t content ./content_service
      - docker build -t interaction ./interaction_service

      # Tag Docker images for ECR
      - docker tag feed:latest 522814711764.dkr.ecr.us-east-1.amazonaws.com/feed:latest
      - docker tag user:latest 522814711764.dkr.ecr.us-east-1.amazonaws.com/user:latest
      - docker tag content:latest 522814711764.dkr.ecr.us-east-1.amazonaws.com/content:latest
      - docker tag interaction:latest 522814711764.dkr.ecr.us-east-1.amazonaws.com/interaction:latest

  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push 522814711764.dkr.ecr.us-east-1.amazonaws.com/feed:latest
      - docker push 522814711764.dkr.ecr.us-east-1.amazonaws.com/user:latest
      - docker push 522814711764.dkr.ecr.us-east-1.amazonaws.com/content:latest
      - docker push 522814711764.dkr.ecr.us-east-1.amazonaws.com/interaction:latest

artifacts:
  files:
    - '**/*'  # You can specify the files you want to output, but it's not typically needed for Docker builds.
