services:
  user_service:
    build:
      context: ./user_service
    container_name: user_service
    ports:
      - "5001:5001"  # Host port 5001 forwards to container port 5000
    networks:
      - app_network

  content_service:
    build:
      context: ./content_service
    container_name: content_service
    ports:
      - "5002:5002"  # Host port 5002 forwards to container port 5000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
