services:
  user_service:
    build:
      context: ./user_service
    container_name: user_service
    ports:
      - "5001:5001"  # Host port 5001 forwards to container port 5000
    networks:
      - app_network

  content_service:
    build:
      context: ./content_service
    container_name: content_service
    ports:
      - "5002:5002"  # Host port 5002 forwards to container port 5000
    networks:
      - app_network

  feed_service:
    build:
      context: ./feed_service
    container_name: feed_service
    ports:
      - "5003:5003"  # Host port 5003 forwards to container port 5000
    networks:
      - app_network

  interaction_service:
    build:
      context: ./interaction_service
    container_name: interaction_service
    ports:
      - "5004:5004"  # Host port 5004 forwards to container port 5000
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
